// Licensed under the Apache License, Version 2.0 or the MIT License.
// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright OxidOS Automotive SRL 2024
//
// Author: Irina Nita <irina.nita@oxidos.io>
// Author: Darius Jipa <darius.jipa@oxidos.io>

use parse::{context::Context, Chip, Component, Ident};
use proc_macro2::Literal;
use quote::{format_ident, quote};
use std::error::Error;
use std::fs::File;
use std::io::{Read, Write};
use std::path::Path;
use std::rc::Rc;

/// Wrapper struct for the context of the Tock platform's `main.rs`, used
/// for parsing the configuration file and generating the code.
///
/// Each main is generic over the chip that the platform is built on.
pub struct TockMain<C: Chip> {
    context: Context<C>,
}

impl<C: Chip + 'static> TockMain<C> {
    /// Create a new [`TockMain`] instance from a serialized configuration, given the path for
    /// the JSON file and the chip that the configuration is based on.
    pub fn from_json<P: AsRef<Path>>(chip: C, path: P) -> Result<Self, Box<dyn Error>> {
        let mut buf = String::new();
        File::open(path)?.read_to_string(&mut buf)?;

        // Retrieve the base user-provided configuration.
        let config = serde_json::from_str::<parse::Configuration<C::Peripherals>>(&buf)?;

        // Parse the resulted configuration for generating a context.
        let context = Context::from_config(chip, config)?;

        Ok(Self { context })
    }

    pub fn write_to_file<P: AsRef<Path>>(&self, path: P) -> Result<(), Box<dyn Error>> {
        let syntax_tree = syn::parse2(self.main_rs()?)?;
        std::fs::File::create(path)?.write_all(prettyplease::unparse(&syntax_tree).as_bytes())?;

        Ok(())
    }

    /// The token stream of the `main.rs` file for the platform.
    fn main_rs(&self) -> Result<proc_macro2::TokenStream, Box<dyn Error>> {
        let imports = self.imports();
        let global_declarations = self.global_declarations()?;
        let board_struct_def = self.struct_definition()?;
        let setup = self.setup()?;
        let main = self.main();

        Ok(quote! {
            //! GENERATED BY TOCKOS CONFIGURATOR.
            #imports
            #global_declarations
            #board_struct_def
            #setup
            #main
        })
    }

    /// Minimum needed imports.
    fn imports(&self) -> proc_macro2::TokenStream {
        quote! {
            #![no_std]
            #![feature(custom_test_frameworks)]
            #![test_runner(test_runner)]
            #![reexport_test_harness_main = "test_main"]
            #![cfg_attr(not(doc), no_main)]

            use kernel::component::Component;
            use kernel::platform::{KernelResources, SyscallDriverLookup};

            pub mod io;
            mod otbn;
            pub mod pinmux_layout;
            #[cfg(test)]
            mod tests;
        }
    }

    /// The `main` function of the module. The whole logic is moved to the `setup`
    /// function.
    fn main(&self) -> proc_macro2::TokenStream {
        let process_count = Literal::usize_unsuffixed(self.context.process_count);

        quote! {
            #[cfg(all(not(feature = "qemu"), feature = "test_sysrst_ctrl"))]
            fn test_sysrst_ctrl(peripherals: &earlgrey::chip::EarlGreyDefaultPeripherals<ChipConfig, crate::pinmux_layout::BoardPinmuxLayout>) {
                crate::pinmux_layout::prepare_wiring_sysrst_ctrl_tests();
                lowrisc::sysrst_ctrl::tests::test_all(
                    &peripherals.sysreset,
                    &peripherals.gpio_port[7],
                    &peripherals.gpio_port[2],
                    &peripherals.gpio_port[20],
                );
            }

            #[cfg(feature = "test_flash_ctrl")]
            fn test_flash(
                flash_ctrl: &'static earlgrey::flash_ctrl::FlashCtrl,
                uart: &'static earlgrey::uart::Uart<'static>,
            ) {
                let flash_page = unsafe {
                    kernel::static_init!(
                        <earlgrey::flash_ctrl::FlashCtrl as kernel::hil::flash::Flash>::Page,
                        <earlgrey::flash_ctrl::FlashCtrl as kernel::hil::flash::Flash>::Page::default()
                    )
                };

                let placeholder_flash_page = unsafe {
                    kernel::static_init!(
                        <earlgrey::flash_ctrl::FlashCtrl as kernel::hil::flash::Flash>::Page,
                        <earlgrey::flash_ctrl::FlashCtrl as kernel::hil::flash::Flash>::Page::default()
                    )
                };

                let page_index_range =
                    earlgrey::flash_ctrl::tests::convert_flash_slice_to_page_position_range(unsafe {
                        core::slice::from_raw_parts(
                            core::ptr::from_ref::<u8>(&_sapps),
                            core::ptr::from_ref::<u8>(&_eapps) as usize
                                - core::ptr::from_ref::<u8>(&_sapps) as usize,
                        )
                    })
                    .unwrap();

                let test_client = unsafe {
                    kernel::static_init!(
                        earlgrey::flash_ctrl::tests::TestClient,
                        earlgrey::flash_ctrl::tests::TestClient::new(
                            flash_ctrl,
                            flash_page,
                            placeholder_flash_page,
                            page_index_range
                        ),
                    )
                };

                earlgrey::flash_ctrl::tests::run_all(flash_ctrl, test_client, uart);
            }

            #[cfg(feature = "test_alerthandler")]
            unsafe fn test_alerthandler(
                peripherals: &'static earlgrey::chip::EarlGreyDefaultPeripherals<ChipConfig, crate::pinmux_layout::BoardPinmuxLayout>,
                mux_alarm: &'static capsules_core::virtualizers::virtual_alarm::MuxAlarm<'static, lowrisc::timer::RvTimer>,
            ) {
                kernel::debug!("Starting AlertHandler test...");
                // an Alarm is needed for some of the tests as alert handling works using interrupts
                let virtual_alarm_tests = kernel::static_init!(
                    capsules_core::virtualizers::virtual_alarm::VirtualMuxAlarm<'static, lowrisc::timer::RvTimer>,
                    capsules_core::virtualizers::virtual_alarm::VirtualMuxAlarm::new(mux_alarm)
                );
                virtual_alarm_tests.setup();

                let alert_handler_tests = kernel::static_init!(
                    earlgrey::alert_handler::tests::Tests<capsules_core::virtualizers::virtual_alarm::VirtualMuxAlarm<'static, lowrisc::timer::RvTimer>>,
                    earlgrey::alert_handler::tests::Tests::new(
                        &peripherals.alert_handler,
                        virtual_alarm_tests,
                        &peripherals.uart0
                    )
                );

                kernel::hil::time::Alarm::set_alarm_client(virtual_alarm_tests, alert_handler_tests);

                alert_handler_tests.run_tests();
                kernel::debug!("Finished AlertHandler tests. Everything is alright!");
            }

            #[cfg(feature = "test_aon_timer")]
            unsafe fn test_aon_timer(
                peripherals: &'static EarlGreyDefaultPeripherals<ChipConfig, BoardPinmuxLayout>,
                mux_alarm: &'static MuxAlarm<'static, RvTimer>,
            ) {
                debug!("Start aon_timer kernel runtime tests!");

                // an Alarm is needed for some of the tests as alert handling works using interrupts
                let virtual_alarm_tests = static_init!(
                    VirtualMuxAlarm<'static, lowrisc::timer::RvTimer>,
                    VirtualMuxAlarm::new(mux_alarm)
                );
                virtual_alarm_tests.setup();

                let aon_timer_tests = static_init!(
                    aon_timer::tests::Tests<VirtualMuxAlarm<'static, RvTimer>>,
                    aon_timer::tests::Tests::new(&peripherals.watchdog, virtual_alarm_tests,)
                );

                hil::time::Alarm::set_alarm_client(virtual_alarm_tests, aon_timer_tests);

                aon_timer_tests.start_alarm(1000);
            }

            /// Entry point for the OpenTitan board.
            ///
            /// # Safety
            ///
            /// This function relies on correct configuration of external
            /// statics.
            #[no_mangle]
            pub unsafe fn main() {
                #[cfg(test)]
                {
                    test_main();
                }

                #[cfg(not(test))]
                {
                    let __main_loop_capability = kernel::create_capability!(kernel::capabilities::MainLoopCapability);
                    let (board_kernel, platform, chip, _peripherals) = setup();
                    kernel::debug!("OpenTitan initialisation complete. Entering main loop");
                    board_kernel.kernel_loop(
                        platform,
                        chip,
                        None::<&kernel::ipc::IPC<#process_count>>,
                        &__main_loop_capability,
                    );
                }
            }

            #[cfg(test)]
            use kernel::platform::watchdog::WatchDog;

            #[cfg(test)]
            fn test_runner(tests: &[&dyn Fn()]) {
                unsafe {
                    let (board_kernel, earlgrey, _chip, peripherals) = setup();

                    BOARD = Some(board_kernel);
                    PLATFORM = Some(earlgrey);
                    PERIPHERALS = Some(peripherals);
                    MAIN_CAP = Some(&kernel::create_capability!(kernel::capabilities::MainLoopCapability));

                    PLATFORM.map(|platform| platform.watchdog().setup());

                    for test in tests {
                        test();
                    }
                }

                crate::tests::semihost_command_exit_success()
            }
        }
    }

    /// Constants and statics.
    fn global_declarations(&self) -> Result<proc_macro2::TokenStream, Box<dyn Error>> {
        let (chip_type, process_count, stack_size) = (
            self.context.chip.ty()?,
            self.context.process_count,
            self.context.stack_size,
        );

        Ok(quote! {
            /// The `earlgrey` chip crate supports multiple targets with slightly different
            /// configurations, which are encoded through implementations of the
            /// `earlgrey::chip_config::EarlGreyConfig` trait. This type provides different
            /// implementations of the `EarlGreyConfig` trait, depending on Cargo's
            /// conditional compilation feature flags. If no feature is selected,
            /// compilation will error.
            enum ChipConfig {}

            #[cfg(feature = "qemu")]
            impl earlgrey::chip_config::EarlGreyConfig for ChipConfig {
                const NAME: &'static str = "qemu";
                const CPU_FREQ: u32 = 24_000_000;
                const PERIPHERAL_FREQ: u32 = 6_000_000;
                const AON_TIMER_FREQ: u64 = 250_000;
                const UART_BAUDRATE: u32 = 115200;
            }

            #[cfg(feature = "fpga")]
            impl earlgrey::chip_config::EarlGreyConfig for ChipConfig {
                const NAME: &'static str = "fpga";
                const CPU_FREQ: u32 = 24_000_000;
                const PERIPHERAL_FREQ: u32 = 6_000_000;
                const AON_TIMER_FREQ: u64 = 250_000;
                const UART_BAUDRATE: u32 = 115200;
            }

            #[cfg(feature = "silicon")]
            impl earlgrey::chip_config::EarlGreyConfig for ChipConfig {
                const NAME: &'static str = "silicon";
                const CPU_FREQ: u32 = 100_000_000;
                const PERIPHERAL_FREQ: u32 = 24_000_000;
                const AON_TIMER_FREQ: u64 = 200_000;
                const UART_BAUDRATE: u32 = 115200;
            }

            #[cfg(feature = "sim_verilator")]
            impl EarlGreyConfig for ChipConfig {
                const NAME: &'static str = "sim_verilator";

                // Clock frequencies as of https://github.com/lowRISC/opentitan/pull/19368
                const CPU_FREQ: u32 = 500_000;
                const PERIPHERAL_FREQ: u32 = 125_000;
                const AON_TIMER_FREQ: u64 = 125_000;
                const UART_BAUDRATE: u32 = 7200;
            }

            #[cfg(feature = "sival")]
            pub type EPMPDebugConfig = earlgrey::epmp::EPMPDebugDisable;
            #[cfg(not(feature = "sival"))]
            pub type EPMPDebugConfig = earlgrey::epmp::EPMPDebugEnable;

            pub const EPMP_HANDOVER_CONFIG_CHECK: bool = false;

            pub const NUM_PROCS: usize = #process_count;
            const FAULT_RESPONSE: capsules_system::process_policies::PanicFaultPolicy = capsules_system::process_policies::PanicFaultPolicy {};
            static mut PROCESSES: [Option<&'static dyn kernel::process::Process>; NUM_PROCS] = [None; NUM_PROCS];
            static mut PROCESS_PRINTER: Option<
                &'static capsules_system::process_printer::ProcessPrinterText,
            > = None;
            type ChipType = #chip_type;
            static mut CHIP: Option<&ChipType> = None;

            // Test access to the peripherals
            #[cfg(test)]
            static mut PERIPHERALS: Option<&'static earlgrey::chip::EarlGreyDefaultPeripherals<ChipConfig, crate::pinmux_layout::BoardPinmuxLayout>> =
                None;
            // Test access to board
            #[cfg(test)]
            static mut BOARD: Option<&'static kernel::Kernel> = None;
            // Test access to platform
            #[cfg(test)]
            static mut PLATFORM: Option<&'static EarlGrey> = None;
            // Test access to main loop capability
            #[cfg(test)]
            static mut MAIN_CAP: Option<&dyn kernel::capabilities::MainLoopCapability> = None;
            // Test access to alarm
            #[cfg(test)]
            static mut ALARM: Option<
                &'static capsules_core::virtualizers::virtual_alarm::MuxAlarm<'static, lowrisc::timer::RvTimer<'static >>,
            > = None;
            // Test access to TicKV
            #[cfg(test)]
            static mut TICKV: Option<
                &capsules_extra::tickv::TicKVSystem<
                    'static,
                    capsules_core::virtualizers::virtual_flash::FlashUser<
                        'static,
                        earlgrey::flash_ctrl::FlashCtrl<'static>,
                    >,
                    capsules_extra::sip_hash::SipHasher24<'static>,
                    2048,
                >,
            > = None;
            // Test access to AES
            #[cfg(test)]
            static mut AES: Option<
                &capsules_aes_gcm::aes_gcm::Aes128Gcm<
                    'static,
                    capsules_core::virtualizers::virtual_aes_ccm::VirtualAES128CCM<'static, earlgrey::aes::Aes<'static>>,
                >,
            > = None;
            // Test access to SipHash
            #[cfg(test)]
            static mut SIPHASH: Option<&capsules_extra::sip_hash::SipHasher24<'static>> = None;
            // Test access to RSA
            #[cfg(test)]
            static mut RSA_HARDWARE: Option<&lowrisc::rsa::OtbnRsa<'static>> = None;

            // Test access to a software SHA256
            #[cfg(test)]
            static mut SHA256SOFT: Option<&capsules_extra::sha256::Sha256Software<'static>> = None;

            #[no_mangle]
            #[link_section = ".stack_buffer"]
            pub static mut STACK_MEMORY: [u8; #stack_size] = [0; #stack_size];

            // These symbols are defined in the linker script.
            extern "C" {
                /// Beginning of the ROM region containing app images.
                static _sapps: u8;
                /// End of the ROM region containing app images.
                static _eapps: u8;
                /// Beginning of the RAM region for app memory.
                static mut _sappmem: u8;
                /// End of the RAM region for app memory.
                static _eappmem: u8;
                /// The start of the kernel text (Included only for kernel PMP)
                static _stext: u8;
                /// The end of the kernel text (Included only for kernel PMP)
                static _etext: u8;
                /// The start of the kernel / app / storage flash (Included only for kernel PMP)
                static _sflash: u8;
                /// The end of the kernel / app / storage flash (Included only for kernel PMP)
                static _eflash: u8;
                /// The start of the kernel / app RAM (Included only for kernel PMP)
                static _ssram: u8;
                /// The end of the kernel / app RAM (Included only for kernel PMP)
                static _esram: u8;
                /// The start of the OpenTitan manifest
                static _manifest: u8;
            }

            fn get_flash_default_memory_protection_region() -> earlgrey::flash_ctrl::DefaultMemoryProtectionRegion {
                if cfg!(feature = "sival") {
                    earlgrey::flash_ctrl::DefaultMemoryProtectionRegion::new()
                        .enable_ecc()
                        .enable_scramble()
                } else {
                    earlgrey::flash_ctrl::DefaultMemoryProtectionRegion::new()
                }
            }

            fn get_flash_memory_protection_configuration() -> earlgrey::flash_ctrl::MemoryProtectionConfiguration {
                let flash_default_memory_protection_region = get_flash_default_memory_protection_region();

                let base_memory_protection_config =
                    earlgrey::flash_ctrl::MemoryProtectionConfiguration::new(flash_default_memory_protection_region);

                #[cfg(feature = "test_flash_ctrl")]
                {
                    let page_index_range =
                        earlgrey::flash_ctrl::tests::convert_flash_slice_to_page_position_range(unsafe {
                            core::slice::from_raw_parts(
                                core::ptr::from_ref(&_sapps),
                                core::ptr::from_ref(&_eapps) as usize - core::ptr::from_ref(&_sapps) as usize,
                            )
                        })
                        .unwrap();

                    use earlgrey::flash_ctrl::DataMemoryProtectionRegionBase;
                    use earlgrey::flash_ctrl::DataMemoryProtectionRegionSize;

                    let memory_protection_page0_base =
                        DataMemoryProtectionRegionBase::new(*page_index_range.end());

                    const RAW_MEMORY_PROTECTION_PAGE0_SIZE: core::num::NonZeroU16 =
                        match core::num::NonZeroU16::new(1) {
                            Some(non_zero_u16) => non_zero_u16,
                            None => unreachable!(),
                        };

                    const MEMORY_PROTECTION_PAGE0_SIZE: DataMemoryProtectionRegionSize =
                        match DataMemoryProtectionRegionSize::new(RAW_MEMORY_PROTECTION_PAGE0_SIZE) {
                            Ok(memory_protection_page0_size) => memory_protection_page0_size,
                            Err(()) => unreachable!(),
                        };

                    base_memory_protection_config
                        .enable_and_configure_data_region(
                            earlgrey::flash_ctrl::DataMemoryProtectionRegionIndex::Index0,
                            memory_protection_page0_base,
                            MEMORY_PROTECTION_PAGE0_SIZE,
                        )
                        .enable_erase()
                        .enable_write()
                        .enable_read()
                        .enable_high_endurance()
                        .finalize_region()
                        .enable_and_configure_info2_region(
                            earlgrey::flash_ctrl::tests::VALID_INFO2_MEMORY_PROTECTION_REGION_INDEX,
                        )
                        .enable_erase()
                        .enable_write()
                        .enable_read()
                        .enable_high_endurance()
                        .finalize_region()
                }
                #[cfg(not(feature = "test_flash_ctrl"))]
                {
                    #[allow(clippy::undocumented_unsafe_blocks)]
                    let starting_address = unsafe {
                        earlgrey::flash_ctrl::FlashAddress::new_from_host_address(&_stext as *const u8)
                            .unwrap()
                    };
                    #[allow(clippy::undocumented_unsafe_blocks)]
                    let ending_address = unsafe {
                        earlgrey::flash_ctrl::FlashAddress::new_from_host_address(&_etext as *const u8)
                            .unwrap()
                    };

                    // Setup flash memory protection for the kernel
                    // PANIC: the unwrap panics only if Flash(_stext) < FlashAddress(_etext), which occurs
                    // only due to a linker script bug.
                    if cfg!(feature = "sival") {
                        base_memory_protection_config
                            .enable_and_configure_data_region_from_pointers(
                                earlgrey::flash_ctrl::DataMemoryProtectionRegionIndex::Index0,
                                starting_address,
                                ending_address,
                            )
                            .unwrap()
                            .enable_read()
                            .enable_scramble()
                            .enable_ecc()
                            .finalize_region()
                            .enable_and_configure_info2_region(
                                earlgrey::flash_ctrl::Info2MemoryProtectionRegionIndex::Bank1(
                                    earlgrey::flash_ctrl::Info2PageIndex::Index1,
                                ),
                            )
                            .enable_read()
                            .enable_write()
                            .enable_erase()
                            .finalize_region()
                    } else {
                        base_memory_protection_config
                            .enable_and_configure_data_region_from_pointers(
                                earlgrey::flash_ctrl::DataMemoryProtectionRegionIndex::Index0,
                                starting_address,
                                ending_address,
                            )
                            .unwrap()
                            .enable_read()
                            .finalize_region()
                            .enable_and_configure_info2_region(
                                earlgrey::flash_ctrl::Info2MemoryProtectionRegionIndex::Bank1(
                                    earlgrey::flash_ctrl::Info2PageIndex::Index1,
                                ),
                            )
                            .enable_read()
                            .enable_write()
                            .enable_erase()
                            .finalize_region()
                    }
                }
            }
        })
    }

    /// Board's setup function.
    fn setup(&self) -> Result<proc_macro2::TokenStream, Box<dyn Error>> {
        let (platform_ty, platform_ident): (_, proc_macro2::TokenStream) = (
            self.context.platform.ty()?,
            self.context.platform.ident()?.parse().unwrap(),
        );

        let chip_ty = self.context.chip.ty()?;
        let chip_ident = format_ident!("{}", self.context.chip.ident()?);

        let peripherals = self.context.chip.peripherals();
        let peripherals_ty = peripherals.ty()?;
        let peripherals_ident = format_ident!("{}", peripherals.ident()?);

        // Stack for the traversed nodes.
        // Contains the "roots" of the graph, i.e. the platform, the chip.
        let mut stack: Vec<Rc<dyn Component>> =
            vec![self.context.platform.clone(), self.context.chip.clone()];

        // Sort the initialization dependencies.
        let initializations = crate::util::topological_sort(&mut stack)?;

        // Inject the custom code for a chip/arch? Like enabling interrupts?
        Ok(quote! {
            type SetupOut = (
                &'static kernel::Kernel,
                &'static #platform_ty,
                &'static #chip_ty,
                &'static #peripherals_ty,
            );
            unsafe fn setup() -> SetupOut {
                // Could be unused if no drivers are included.
                #[allow(unused)]
                let memory_allocation_cap = kernel::create_capability!(kernel::capabilities::MemoryAllocationCapability);
                let board_kernel = kernel::static_init!(kernel::Kernel, kernel::Kernel::new(&*core::ptr::addr_of!(PROCESSES)));
                #(#initializations)*

                #[cfg(test)]
                {
                    use capsules_extra::sha256::Sha256Software;
                    let sha_soft = kernel::static_init!(Sha256Software<'static>, Sha256Software::new());
                    kernel::deferred_call::DeferredCallClient::register(sha_soft);

                    SHA256SOFT = Some(sha_soft);

                    let mux_otbn = crate::otbn::AccelMuxComponent::new(&peripherals.otbn)
                        .finalize(otbn_mux_component_static!());

                    let otbn = crate::otbn::OtbnComponent::new(mux_otbn).finalize(crate::otbn_component_static!());

                    let otbn_rsa_internal_buf = kernel::static_init!([u8; 512], [0; 512]);

                    // Use the OTBN to create an RSA engine
                    if let Ok((rsa_imem_start, rsa_imem_length, rsa_dmem_start, rsa_dmem_length)) =
                        crate::otbn::find_app(
                            "otbn-rsa",
                            core::slice::from_raw_parts(
                                core::ptr::addr_of!(_sapps),
                                core::ptr::addr_of!(_eapps) as usize - core::ptr::addr_of!(_sapps) as usize,
                            ),
                        )
                    {
                        let rsa_hardware = kernel::static_init!(
                            lowrisc::rsa::OtbnRsa<'static>,
                            lowrisc::rsa::OtbnRsa::new(
                                otbn,
                                lowrisc::rsa::AppAddresses {
                                    imem_start: rsa_imem_start,
                                    imem_size: rsa_imem_length,
                                    dmem_start: rsa_dmem_start,
                                    dmem_size: rsa_dmem_length
                                },
                                otbn_rsa_internal_buf,
                            )
                        );
                        peripherals.otbn.set_client(rsa_hardware);
                        RSA_HARDWARE = Some(rsa_hardware);
                    } else {
                        kernel::debug!("Unable to find otbn-rsa, disabling RSA support");
                    }
                }

                let __process_management_capability =
                    kernel::create_capability!(kernel::capabilities::ProcessManagementCapability);
                    extern "C" {
                        static _sapps: u8;
                        static _eapps: u8;
                        static mut _sappmem: u8;
                        static _eappmem: u8;
                    }

                #[cfg(all(not(feature = "sival"), feature = "test_otp"))]
                {
                    lowrisc::otp::tests::run_all(&peripherals.otp);
                }

                #[cfg(feature = "test_pattgen")]
                {
                    let pattgen_test = static_init!(
                        lowrisc::pattgen::tests::PattGenTest,
                        lowrisc::pattgen::tests::PattGenTest::new(&peripherals.pattgen),
                    );
                    lowrisc::pattgen::tests::run_all(pattgen_test);
                }

                #[cfg(feature = "test_flash_ctrl")]
                test_flash(&peripherals.flash_ctrl, &peripherals.uart0);

                #[cfg(feature = "test_alerthandler")]
                {
                    test_alerthandler(peripherals, mux_alarm);
                }

                #[cfg(all(not(feature = "qemu"), feature = "test_sysrst_ctrl"))]
                {
                    test_sysrst_ctrl(peripherals);
                }

                #[cfg(all(not(feature = "qemu"), feature = "test_resetmanager"))]
                capsules_extra::reset_manager::test::test_software_reset(
                    &peripherals.sram_ret,
                    earlgrey.reset_manager,
                    core::ptr::addr_of!(_sflash) as usize,
                    core::ptr::addr_of!(_eflash) as usize,
                );

                #[cfg(all(not(feature = "qemu"), feature = "test_sram_ret"))]
                peripherals
                    .sram_ret
                    .test(&peripherals.rst_mgmt, &peripherals.uart0);

                #[cfg(all(not(feature = "qemu"), feature = "test_aon_timer"))]
                {
                    peripherals.watchdog.test(
                        &peripherals.uart0,
                        &peripherals.sram_ret,
                        &peripherals.sram_ret,
                    );
                    test_aon_timer(peripherals, mux_alarm);
                }

                kernel::process::load_processes(
                    board_kernel,
                    #chip_ident,
                    core::slice::from_raw_parts(
                        core::ptr::addr_of!(_sapps),
                        core::ptr::addr_of!(_eapps) as usize - core::ptr::addr_of!(_sapps) as usize,
                    ),
                    core::slice::from_raw_parts_mut(
                        core::ptr::addr_of_mut!(_sappmem),
                        core::ptr::addr_of!(_eappmem) as usize - core::ptr::addr_of!(_sappmem) as usize,
                    ),
                    &mut *core::ptr::addr_of_mut!(PROCESSES),
                    &FAULT_RESPONSE,
                    &__process_management_capability,
                )
                .unwrap_or_else(|err| {
                    kernel::debug!("Error loading processes!");
                    kernel::debug!("{:?}", err);
                });

                (board_kernel, #platform_ident, #chip_ident, #peripherals_ident)
            }
        })
    }

    /// Definition of the board's struct and implementations of the needed traits.
    fn struct_definition(&self) -> Result<proc_macro2::TokenStream, Box<dyn Error>> {
        let (scheduler_timer_id, scheduler_timer_type) = (
            format_ident!("{}", self.context.chip.systick()?.ident()?),
            self.context.chip.systick()?.ty()?,
        );
        let board_ty = self.context.platform.ty()?;
        let (scheduler_id, scheduler_ty) = (
            format_ident!("{}", self.context.platform.scheduler.ident()?),
            self.context.platform.scheduler.ty()?,
        );

        let (watchdog_id, watchdog_ty) = (
            format_ident!("{}", self.context.platform.watchdog.ident()?),
            self.context.platform.watchdog.ty()?,
        );

        let chip_ty = self.context.chip.ty()?;

        let capsules = &self.context.platform.capsules;

        let mut capsules_identifiers = Vec::new();
        let mut capsules_types = Vec::new();
        let mut capsules_driver_nums = Vec::new();

        for capsule in capsules.iter() {
            capsules_identifiers.push(format_ident!("{}", capsule.ident()?.to_string()));
            capsules_types.push(capsule.ty()?);
            capsules_driver_nums.push(capsule.driver_num());
        }

        Ok(quote! {
            // This `#[allow]` is required because the configuration file may
            // contain a non-camelcase config name.
            #[allow(non_camel_case_types)]
            struct #board_ty {
                #(#capsules_identifiers: &'static #capsules_types,)*
                #scheduler_id: &'static #scheduler_ty,
                #scheduler_timer_id: &'static #scheduler_timer_type,
                #watchdog_id: &'static #watchdog_ty,
            }

            impl SyscallDriverLookup for #board_ty {
                fn with_driver<F, R>(&self, driver_num: usize, f: F) -> R
                where
                    F: FnOnce(Option<&dyn kernel::syscall::SyscallDriver>) -> R,
                {
                    // Don't flag verbosity for single binding if no capsules are included.
                    #[allow(clippy::match_single_binding)]
                    match driver_num {
                        #( #capsules_driver_nums => f(Some(self.#capsules_identifiers)),)*
                        _ => f(None),
                    }
                }
            }

            impl KernelResources<#chip_ty> for #board_ty {
                type SyscallDriverLookup = Self;
                type SyscallFilter = ();
                type ProcessFault = ();
                type Scheduler = #scheduler_ty;
                type SchedulerTimer = #scheduler_timer_type;
                type WatchDog = #watchdog_ty;
                type ContextSwitchCallback = ();

                fn syscall_driver_lookup(&self) -> &Self::SyscallDriverLookup {
                    self
                }
                fn syscall_filter(&self) -> &Self::SyscallFilter {
                    &()
                }
                fn process_fault(&self) -> &Self::ProcessFault {
                    &()
                }
                fn scheduler(&self) -> &Self::Scheduler {
                    self.#scheduler_id
                }
                fn scheduler_timer(&self) -> &Self::SchedulerTimer {
                    self.#scheduler_timer_id
                }
                fn watchdog(&self) -> &Self::WatchDog {
                    self.#watchdog_id
                }
                fn context_switch_callback(&self) -> &Self::ContextSwitchCallback {
                    &()
                }
            }
        })
    }
}
