// Licensed under the Apache License, Version 2.0 or the MIT License.
// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright Tock Contributors 2022.
//
// Copyright zeroRISC Inc.
// Confidential information of zeroRISC Inc. All rights reserved.

use crate::{items, state, Opts};

/// Runs the configurator without a GUI based on the command-line arguments.
pub fn run_cli_mode(mut opts: Opts) {
    // TODO: Parse capsule configuration files.
    let mut data = run_cli_inner(&mut opts);
    // Write JSON output
    opts.out.map(|out| data.set_out(out));
    state::write_json(&mut data);
}

fn run_cli_inner(opts: &mut Opts) -> state::Data<lowrisc::Chip> {
    let mut data = state::Data::new(match opts.chip {
        items::SupportedChip::EarlgreyCw310 => lowrisc::Chip::new(),
    });

    // Record platform name
    data.platform
        .update_type(std::mem::take(&mut opts.platform));
    // Record stack size
    data.platform.update_stack_size(opts.stack_size);
    // Record scheduler
    data.platform.update_scheduler(opts.scheduler);
    // Record syscall filter
    data.platform.update_syscall_filter(opts.syscall_filter);
    // Record process count
    data.platform.process_count = opts.processes;
    // TODO: Parse capsule data
    data
}

#[cfg(test)]
mod tests {
    use crate::cli::run_cli_inner;
    use crate::items::SupportedChip;
    use crate::{Mode, Opts};
    use std::collections::HashMap;
    use std::path::PathBuf;

    /// Checks the configurator outputs the expected JSON configuration format
    /// in a basic case with no capsules.
    #[test]
    fn test_basic() {
        let mut opts = Opts {
            mode: Mode::Cli,
            chip: SupportedChip::EarlgreyCw310,
            platform: String::from("AutogeneratedPlatform"),
            stack_size: 2000,
            scheduler: parse::SchedulerType::Cooperative,
            syscall_filter: parse::SyscallFilterType::None,
            processes: 0,
            capsules: vec![],
            out: None,
        };
        let expected = r#"{
  "TYPE": "AutogeneratedPlatform",
  "CAPSULES": {},
  "SCHEDULER": "Cooperative",
  "PROCESS_COUNT": 0,
  "STACK_SIZE": 2000,
  "SYSCALL_FILTER": "None"
}"#;
        let data = run_cli_inner(&mut opts);
        let board_config = serde_json::to_string_pretty(&data.platform).unwrap();
        assert_eq!(
            expected,
            board_config.as_str(),
            "Board config did not match expected value"
        )
    }

    /// Checks the configurator respects the specified platform name.
    #[test]
    fn test_platform_name() {
        let mut opts = Opts {
            mode: Mode::Cli,
            chip: SupportedChip::EarlgreyCw310,
            platform: String::from("TestPlatformName"),
            stack_size: 2000,
            scheduler: parse::SchedulerType::Cooperative,
            syscall_filter: parse::SyscallFilterType::None,
            processes: 0,
            capsules: vec![],
            out: None,
        };
        let expected = r#"{
  "TYPE": "TestPlatformName",
  "CAPSULES": {},
  "SCHEDULER": "Cooperative",
  "PROCESS_COUNT": 0,
  "STACK_SIZE": 2000,
  "SYSCALL_FILTER": "None"
}"#;
        let data = run_cli_inner(&mut opts);
        let board_config = serde_json::to_string_pretty(&data.platform).unwrap();
        assert_eq!(
            expected,
            board_config.as_str(),
            "Board config did not match expected value"
        )
    }

    /// Checks the configurator respects the specified stack size.
    #[test]
    fn test_stack_size() {
        let mut opts = Opts {
            mode: Mode::Cli,
            chip: SupportedChip::EarlgreyCw310,
            platform: String::from("AutogeneratedPlatform"),
            stack_size: usize::try_from(u32::MAX).unwrap(),
            scheduler: parse::SchedulerType::Cooperative,
            syscall_filter: parse::SyscallFilterType::None,
            processes: 0,
            capsules: vec![],
            out: None,
        };
        let expected = r#"{
  "TYPE": "AutogeneratedPlatform",
  "CAPSULES": {},
  "SCHEDULER": "Cooperative",
  "PROCESS_COUNT": 0,
  "STACK_SIZE": 4294967295,
  "SYSCALL_FILTER": "None"
}"#;
        let data = run_cli_inner(&mut opts);
        let board_config = serde_json::to_string_pretty(&data.platform).unwrap();
        assert_eq!(
            expected,
            board_config.as_str(),
            "Board config did not match expected value"
        )
    }
    /// Checks the configurator respects the specified scheduler.
    #[test]
    fn test_scheduler() {
        let mut opts = Opts {
            mode: Mode::Cli,
            chip: SupportedChip::EarlgreyCw310,
            platform: String::from("AutogeneratedPlatform"),
            stack_size: 2000,
            scheduler: parse::SchedulerType::RoundRobin,
            syscall_filter: parse::SyscallFilterType::None,
            processes: 0,
            capsules: vec![],
            out: None,
        };
        let expected = r#"{
  "TYPE": "AutogeneratedPlatform",
  "CAPSULES": {},
  "SCHEDULER": "RoundRobin",
  "PROCESS_COUNT": 0,
  "STACK_SIZE": 2000,
  "SYSCALL_FILTER": "None"
}"#;
        let data = run_cli_inner(&mut opts);
        let board_config = serde_json::to_string_pretty(&data.platform).unwrap();
        assert_eq!(
            expected,
            board_config.as_str(),
            "Board config did not match expected value"
        )
    }
    /// Checks the configurator respects the specified syscall filter type.
    #[test]
    fn test_syscall_filter_type() {
        let mut opts = Opts {
            mode: Mode::Cli,
            chip: SupportedChip::EarlgreyCw310,
            platform: String::from("AutogeneratedPlatform"),
            stack_size: 2000,
            scheduler: parse::SchedulerType::Cooperative,
            syscall_filter: parse::SyscallFilterType::TbfHeaderFilterDefaultAllow,
            processes: 0,
            capsules: vec![],
            out: None,
        };
        let expected = r#"{
  "TYPE": "AutogeneratedPlatform",
  "CAPSULES": {},
  "SCHEDULER": "Cooperative",
  "PROCESS_COUNT": 0,
  "STACK_SIZE": 2000,
  "SYSCALL_FILTER": "TbfHeaderFilterDefaultAllow"
}"#;
        let data = run_cli_inner(&mut opts);
        let board_config = serde_json::to_string_pretty(&data.platform).unwrap();
        assert_eq!(
            expected,
            board_config.as_str(),
            "Board config did not match expected value"
        )
    }

    /// Checks the configurator respects the specified process count.
    #[test]
    fn test_process_count() {
        let mut opts = Opts {
            mode: Mode::Cli,
            chip: SupportedChip::EarlgreyCw310,
            platform: String::from("AutogeneratedPlatform"),
            stack_size: 2000,
            scheduler: parse::SchedulerType::Cooperative,
            syscall_filter: parse::SyscallFilterType::None,
            processes: usize::try_from(u32::MAX).unwrap(),
            capsules: vec![],
            out: None,
        };
        let expected = r#"{
  "TYPE": "AutogeneratedPlatform",
  "CAPSULES": {},
  "SCHEDULER": "Cooperative",
  "PROCESS_COUNT": 4294967295,
  "STACK_SIZE": 2000,
  "SYSCALL_FILTER": "None"
}"#;
        let data = run_cli_inner(&mut opts);
        let board_config = serde_json::to_string_pretty(&data.platform).unwrap();
        assert_eq!(
            expected,
            board_config.as_str(),
            "Board config did not match expected value"
        )
    }
}
