// Licensed under the Apache License, Version 2.0 or the MIT License.
// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright OxidOS Automotive SRL 2024
//
// Author: Irina Nita <irina.nita@oxidos.io>
// Author: Darius Jipa <darius.jipa@oxidos.io>

//! Utils used for the configurator TUI.

use clap::{Parser, ValueEnum};
use std::path::PathBuf;
mod capsule;
mod cli;
mod menu;
mod state;
mod utils;

// Reimports
pub use cli::run_cli_mode;
pub use menu::init_configurator as init;
pub(crate) use utils::*;

#[derive(Debug, Parser)]
pub struct Opts {
    /// Whether to use the GUI or CLI mode
    #[arg(long, value_enum, default_value_t)]
    pub mode: Mode,

    /// The chip to use.
    #[arg(long, value_enum, default_value_t)]
    chip: utils::items::SupportedChip,

    /// The platform name to include in output JSON
    #[arg(long, default_value = "AutogeneratedPlatform")]
    platform: String,

    /// The kernel stack size.
    #[arg(long, default_value_t = 0x900)]
    stack_size: usize,

    /// Which scheduler to use.
    #[arg(long, value_enum, default_value_t)]
    scheduler: parse::SchedulerType,

    /// Syscall filter type to use.
    #[arg(long, value_enum, default_value_t)]
    syscall_filter: parse::SyscallFilterType,

    /// Number of processes
    #[arg(short, long, default_value_t)]
    processes: usize,

    /// String containing one or more paths to capsule configuration files to include, separated by
    /// spaces. The argument can be provided more than once.
    #[arg(long)]
    capsules: Vec<String>,

    /// File to write the output config.
    #[arg(short, long)]
    out: Option<PathBuf>,
}

/// Whether to use the GUI or CLI mode
#[derive(Clone, Copy, Debug, Default, ValueEnum)]
pub enum Mode {
    /// Run the graphical interface.
    #[default]
    Gui,
    /// Run the command-line interface.
    Cli,
}
