// Licensed under the Apache License, Version 2.0 or the MIT License.
// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright lowRISC contributors (OpenTitan project).

// Generated register constants for otp_ctrl.
// Original reference file: hw/ip/otp_ctrl/data/otp_ctrl.hjson
use kernel::utilities::registers::ReadOnly;
use kernel::utilities::registers::ReadWrite;
use kernel::utilities::registers::{register_bitfields, register_structs};
/// Number of key slots
pub const OTP_CTRL_PARAM_NUM_SRAM_KEY_REQ_SLOTS: u32 = 4;
/// Width of the OTP byte address.
pub const OTP_CTRL_PARAM_OTP_BYTE_ADDR_WIDTH: u32 = 11;
/// Number of error register entries.
pub const OTP_CTRL_PARAM_NUM_ERROR_ENTRIES: u32 = 13;
/// Number of 32bit words in the DAI.
pub const OTP_CTRL_PARAM_NUM_DAI_WORDS: u32 = 2;
/// Size of the digest fields in 32bit words.
pub const OTP_CTRL_PARAM_NUM_DIGEST_WORDS: u32 = 2;
/// Size of the TL-UL window in 32bit words. Note that the effective partition size is smaller
/// than that.
pub const OTP_CTRL_PARAM_NUM_SW_CFG_WINDOW_WORDS: u32 = 512;
/// Number of partitions
pub const OTP_CTRL_PARAM_NUM_PART: u32 = 11;
/// Number of unbuffered partitions
pub const OTP_CTRL_PARAM_NUM_PART_UNBUF: u32 = 5;
/// Number of buffered partitions (including 1 lifecycle partition)
pub const OTP_CTRL_PARAM_NUM_PART_BUF: u32 = 6;
/// Offset of the VENDOR_TEST partition
pub const OTP_CTRL_PARAM_VENDOR_TEST_OFFSET: usize = 0;
/// Size of the VENDOR_TEST partition
pub const OTP_CTRL_PARAM_VENDOR_TEST_SIZE: u32 = 64;
/// Offset of SCRATCH
pub const OTP_CTRL_PARAM_SCRATCH_OFFSET: usize = 0;
/// Size of SCRATCH
pub const OTP_CTRL_PARAM_SCRATCH_SIZE: u32 = 56;
/// Offset of VENDOR_TEST_DIGEST
pub const OTP_CTRL_PARAM_VENDOR_TEST_DIGEST_OFFSET: usize = 56;
/// Size of VENDOR_TEST_DIGEST
pub const OTP_CTRL_PARAM_VENDOR_TEST_DIGEST_SIZE: u32 = 8;
/// Offset of the CREATOR_SW_CFG partition
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_OFFSET: usize = 64;
/// Size of the CREATOR_SW_CFG partition
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_SIZE: u32 = 368;
/// Offset of CREATOR_SW_CFG_AST_CFG
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_AST_CFG_OFFSET: usize = 64;
/// Size of CREATOR_SW_CFG_AST_CFG
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_AST_CFG_SIZE: u32 = 156;
/// Offset of CREATOR_SW_CFG_AST_INIT_EN
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_AST_INIT_EN_OFFSET: usize = 220;
/// Size of CREATOR_SW_CFG_AST_INIT_EN
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_AST_INIT_EN_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_ROM_EXT_SKU
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_ROM_EXT_SKU_OFFSET: usize = 224;
/// Size of CREATOR_SW_CFG_ROM_EXT_SKU
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_ROM_EXT_SKU_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_SIGVERIFY_SPX_EN
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_SIGVERIFY_SPX_EN_OFFSET: usize = 228;
/// Size of CREATOR_SW_CFG_SIGVERIFY_SPX_EN
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_SIGVERIFY_SPX_EN_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_FLASH_DATA_DEFAULT_CFG
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_FLASH_DATA_DEFAULT_CFG_OFFSET: usize = 232;
/// Size of CREATOR_SW_CFG_FLASH_DATA_DEFAULT_CFG
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_FLASH_DATA_DEFAULT_CFG_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_FLASH_INFO_BOOT_DATA_CFG
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_FLASH_INFO_BOOT_DATA_CFG_OFFSET: usize = 236;
/// Size of CREATOR_SW_CFG_FLASH_INFO_BOOT_DATA_CFG
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_FLASH_INFO_BOOT_DATA_CFG_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_FLASH_HW_INFO_CFG_OVERRIDE
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_FLASH_HW_INFO_CFG_OVERRIDE_OFFSET: usize = 240;
/// Size of CREATOR_SW_CFG_FLASH_HW_INFO_CFG_OVERRIDE
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_FLASH_HW_INFO_CFG_OVERRIDE_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_RNG_EN
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RNG_EN_OFFSET: usize = 244;
/// Size of CREATOR_SW_CFG_RNG_EN
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RNG_EN_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_JITTER_EN
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_JITTER_EN_OFFSET: usize = 248;
/// Size of CREATOR_SW_CFG_JITTER_EN
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_JITTER_EN_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_RET_RAM_RESET_MASK
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RET_RAM_RESET_MASK_OFFSET: usize = 252;
/// Size of CREATOR_SW_CFG_RET_RAM_RESET_MASK
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RET_RAM_RESET_MASK_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_MANUF_STATE
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_MANUF_STATE_OFFSET: usize = 256;
/// Size of CREATOR_SW_CFG_MANUF_STATE
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_MANUF_STATE_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_ROM_EXEC_EN
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_ROM_EXEC_EN_OFFSET: usize = 260;
/// Size of CREATOR_SW_CFG_ROM_EXEC_EN
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_ROM_EXEC_EN_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_CPUCTRL
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_CPUCTRL_OFFSET: usize = 264;
/// Size of CREATOR_SW_CFG_CPUCTRL
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_CPUCTRL_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_MIN_SEC_VER_ROM_EXT
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_MIN_SEC_VER_ROM_EXT_OFFSET: usize = 268;
/// Size of CREATOR_SW_CFG_MIN_SEC_VER_ROM_EXT
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_MIN_SEC_VER_ROM_EXT_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_MIN_SEC_VER_BL0
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_MIN_SEC_VER_BL0_OFFSET: usize = 272;
/// Size of CREATOR_SW_CFG_MIN_SEC_VER_BL0
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_MIN_SEC_VER_BL0_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_DEFAULT_BOOT_DATA_IN_PROD_EN
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_DEFAULT_BOOT_DATA_IN_PROD_EN_OFFSET: usize = 276;
/// Size of CREATOR_SW_CFG_DEFAULT_BOOT_DATA_IN_PROD_EN
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_DEFAULT_BOOT_DATA_IN_PROD_EN_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_RMA_SPIN_EN
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RMA_SPIN_EN_OFFSET: usize = 280;
/// Size of CREATOR_SW_CFG_RMA_SPIN_EN
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RMA_SPIN_EN_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_RMA_SPIN_CYCLES
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RMA_SPIN_CYCLES_OFFSET: usize = 284;
/// Size of CREATOR_SW_CFG_RMA_SPIN_CYCLES
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RMA_SPIN_CYCLES_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_RNG_REPCNT_THRESHOLDS
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RNG_REPCNT_THRESHOLDS_OFFSET: usize = 288;
/// Size of CREATOR_SW_CFG_RNG_REPCNT_THRESHOLDS
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RNG_REPCNT_THRESHOLDS_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_RNG_REPCNTS_THRESHOLDS
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RNG_REPCNTS_THRESHOLDS_OFFSET: usize = 292;
/// Size of CREATOR_SW_CFG_RNG_REPCNTS_THRESHOLDS
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RNG_REPCNTS_THRESHOLDS_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_RNG_ADAPTP_HI_THRESHOLDS
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RNG_ADAPTP_HI_THRESHOLDS_OFFSET: usize = 296;
/// Size of CREATOR_SW_CFG_RNG_ADAPTP_HI_THRESHOLDS
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RNG_ADAPTP_HI_THRESHOLDS_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_RNG_ADAPTP_LO_THRESHOLDS
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RNG_ADAPTP_LO_THRESHOLDS_OFFSET: usize = 300;
/// Size of CREATOR_SW_CFG_RNG_ADAPTP_LO_THRESHOLDS
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RNG_ADAPTP_LO_THRESHOLDS_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_RNG_BUCKET_THRESHOLDS
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RNG_BUCKET_THRESHOLDS_OFFSET: usize = 304;
/// Size of CREATOR_SW_CFG_RNG_BUCKET_THRESHOLDS
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RNG_BUCKET_THRESHOLDS_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_RNG_MARKOV_HI_THRESHOLDS
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RNG_MARKOV_HI_THRESHOLDS_OFFSET: usize = 308;
/// Size of CREATOR_SW_CFG_RNG_MARKOV_HI_THRESHOLDS
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RNG_MARKOV_HI_THRESHOLDS_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_RNG_MARKOV_LO_THRESHOLDS
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RNG_MARKOV_LO_THRESHOLDS_OFFSET: usize = 312;
/// Size of CREATOR_SW_CFG_RNG_MARKOV_LO_THRESHOLDS
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RNG_MARKOV_LO_THRESHOLDS_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_RNG_EXTHT_HI_THRESHOLDS
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RNG_EXTHT_HI_THRESHOLDS_OFFSET: usize = 316;
/// Size of CREATOR_SW_CFG_RNG_EXTHT_HI_THRESHOLDS
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RNG_EXTHT_HI_THRESHOLDS_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_RNG_EXTHT_LO_THRESHOLDS
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RNG_EXTHT_LO_THRESHOLDS_OFFSET: usize = 320;
/// Size of CREATOR_SW_CFG_RNG_EXTHT_LO_THRESHOLDS
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RNG_EXTHT_LO_THRESHOLDS_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_RNG_ALERT_THRESHOLD
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RNG_ALERT_THRESHOLD_OFFSET: usize = 324;
/// Size of CREATOR_SW_CFG_RNG_ALERT_THRESHOLD
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RNG_ALERT_THRESHOLD_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_RNG_HEALTH_CONFIG_DIGEST
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RNG_HEALTH_CONFIG_DIGEST_OFFSET: usize = 328;
/// Size of CREATOR_SW_CFG_RNG_HEALTH_CONFIG_DIGEST
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RNG_HEALTH_CONFIG_DIGEST_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_SRAM_KEY_RENEW_EN
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_SRAM_KEY_RENEW_EN_OFFSET: usize = 332;
/// Size of CREATOR_SW_CFG_SRAM_KEY_RENEW_EN
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_SRAM_KEY_RENEW_EN_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_IMMUTABLE_ROM_EXT_EN
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_IMMUTABLE_ROM_EXT_EN_OFFSET: usize = 336;
/// Size of CREATOR_SW_CFG_IMMUTABLE_ROM_EXT_EN
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_IMMUTABLE_ROM_EXT_EN_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_IMMUTABLE_ROM_EXT_START_OFFSET
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_IMMUTABLE_ROM_EXT_START_OFFSET_OFFSET: usize = 340;
/// Size of CREATOR_SW_CFG_IMMUTABLE_ROM_EXT_START_OFFSET
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_IMMUTABLE_ROM_EXT_START_OFFSET_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_IMMUTABLE_ROM_EXT_LENGTH
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_IMMUTABLE_ROM_EXT_LENGTH_OFFSET: usize = 344;
/// Size of CREATOR_SW_CFG_IMMUTABLE_ROM_EXT_LENGTH
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_IMMUTABLE_ROM_EXT_LENGTH_SIZE: u32 = 4;
/// Offset of CREATOR_SW_CFG_IMMUTABLE_ROM_EXT_SHA256_HASH
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_IMMUTABLE_ROM_EXT_SHA256_HASH_OFFSET: usize = 348;
/// Size of CREATOR_SW_CFG_IMMUTABLE_ROM_EXT_SHA256_HASH
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_IMMUTABLE_ROM_EXT_SHA256_HASH_SIZE: u32 = 32;
/// Offset of CREATOR_SW_CFG_RESERVED
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RESERVED_OFFSET: usize = 380;
/// Size of CREATOR_SW_CFG_RESERVED
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_RESERVED_SIZE: u32 = 32;
/// Offset of CREATOR_SW_CFG_DIGEST
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_DIGEST_OFFSET: usize = 424;
/// Size of CREATOR_SW_CFG_DIGEST
pub const OTP_CTRL_PARAM_CREATOR_SW_CFG_DIGEST_SIZE: u32 = 8;
/// Offset of the OWNER_SW_CFG partition
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_OFFSET: usize = 432;
/// Size of the OWNER_SW_CFG partition
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_SIZE: u32 = 712;
/// Offset of OWNER_SW_CFG_ROM_ERROR_REPORTING
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_ERROR_REPORTING_OFFSET: usize = 432;
/// Size of OWNER_SW_CFG_ROM_ERROR_REPORTING
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_ERROR_REPORTING_SIZE: u32 = 4;
/// Offset of OWNER_SW_CFG_ROM_BOOTSTRAP_DIS
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_BOOTSTRAP_DIS_OFFSET: usize = 436;
/// Size of OWNER_SW_CFG_ROM_BOOTSTRAP_DIS
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_BOOTSTRAP_DIS_SIZE: u32 = 4;
/// Offset of OWNER_SW_CFG_ROM_ALERT_CLASS_EN
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_ALERT_CLASS_EN_OFFSET: usize = 440;
/// Size of OWNER_SW_CFG_ROM_ALERT_CLASS_EN
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_ALERT_CLASS_EN_SIZE: u32 = 4;
/// Offset of OWNER_SW_CFG_ROM_ALERT_ESCALATION
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_ALERT_ESCALATION_OFFSET: usize = 444;
/// Size of OWNER_SW_CFG_ROM_ALERT_ESCALATION
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_ALERT_ESCALATION_SIZE: u32 = 4;
/// Offset of OWNER_SW_CFG_ROM_ALERT_CLASSIFICATION
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_ALERT_CLASSIFICATION_OFFSET: usize = 448;
/// Size of OWNER_SW_CFG_ROM_ALERT_CLASSIFICATION
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_ALERT_CLASSIFICATION_SIZE: u32 = 320;
/// Offset of OWNER_SW_CFG_ROM_LOCAL_ALERT_CLASSIFICATION
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_LOCAL_ALERT_CLASSIFICATION_OFFSET: usize = 768;
/// Size of OWNER_SW_CFG_ROM_LOCAL_ALERT_CLASSIFICATION
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_LOCAL_ALERT_CLASSIFICATION_SIZE: u32 = 64;
/// Offset of OWNER_SW_CFG_ROM_ALERT_ACCUM_THRESH
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_ALERT_ACCUM_THRESH_OFFSET: usize = 832;
/// Size of OWNER_SW_CFG_ROM_ALERT_ACCUM_THRESH
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_ALERT_ACCUM_THRESH_SIZE: u32 = 16;
/// Offset of OWNER_SW_CFG_ROM_ALERT_TIMEOUT_CYCLES
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_ALERT_TIMEOUT_CYCLES_OFFSET: usize = 848;
/// Size of OWNER_SW_CFG_ROM_ALERT_TIMEOUT_CYCLES
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_ALERT_TIMEOUT_CYCLES_SIZE: u32 = 16;
/// Offset of OWNER_SW_CFG_ROM_ALERT_PHASE_CYCLES
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_ALERT_PHASE_CYCLES_OFFSET: usize = 864;
/// Size of OWNER_SW_CFG_ROM_ALERT_PHASE_CYCLES
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_ALERT_PHASE_CYCLES_SIZE: u32 = 64;
/// Offset of OWNER_SW_CFG_ROM_ALERT_DIGEST_PROD
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_ALERT_DIGEST_PROD_OFFSET: usize = 928;
/// Size of OWNER_SW_CFG_ROM_ALERT_DIGEST_PROD
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_ALERT_DIGEST_PROD_SIZE: u32 = 4;
/// Offset of OWNER_SW_CFG_ROM_ALERT_DIGEST_PROD_END
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_ALERT_DIGEST_PROD_END_OFFSET: usize = 932;
/// Size of OWNER_SW_CFG_ROM_ALERT_DIGEST_PROD_END
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_ALERT_DIGEST_PROD_END_SIZE: u32 = 4;
/// Offset of OWNER_SW_CFG_ROM_ALERT_DIGEST_DEV
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_ALERT_DIGEST_DEV_OFFSET: usize = 936;
/// Size of OWNER_SW_CFG_ROM_ALERT_DIGEST_DEV
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_ALERT_DIGEST_DEV_SIZE: u32 = 4;
/// Offset of OWNER_SW_CFG_ROM_ALERT_DIGEST_RMA
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_ALERT_DIGEST_RMA_OFFSET: usize = 940;
/// Size of OWNER_SW_CFG_ROM_ALERT_DIGEST_RMA
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_ALERT_DIGEST_RMA_SIZE: u32 = 4;
/// Offset of OWNER_SW_CFG_ROM_WATCHDOG_BITE_THRESHOLD_CYCLES
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_WATCHDOG_BITE_THRESHOLD_CYCLES_OFFSET: usize = 944;
/// Size of OWNER_SW_CFG_ROM_WATCHDOG_BITE_THRESHOLD_CYCLES
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_WATCHDOG_BITE_THRESHOLD_CYCLES_SIZE: u32 = 4;
/// Offset of OWNER_SW_CFG_ROM_KEYMGR_OTP_MEAS_EN
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_KEYMGR_OTP_MEAS_EN_OFFSET: usize = 948;
/// Size of OWNER_SW_CFG_ROM_KEYMGR_OTP_MEAS_EN
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_KEYMGR_OTP_MEAS_EN_SIZE: u32 = 4;
/// Offset of OWNER_SW_CFG_MANUF_STATE
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_MANUF_STATE_OFFSET: usize = 952;
/// Size of OWNER_SW_CFG_MANUF_STATE
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_MANUF_STATE_SIZE: u32 = 4;
/// Offset of OWNER_SW_CFG_ROM_RSTMGR_INFO_EN
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_RSTMGR_INFO_EN_OFFSET: usize = 956;
/// Size of OWNER_SW_CFG_ROM_RSTMGR_INFO_EN
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_RSTMGR_INFO_EN_SIZE: u32 = 4;
/// Offset of OWNER_SW_CFG_ROM_EXT_BOOTSTRAP_EN
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_EXT_BOOTSTRAP_EN_OFFSET: usize = 960;
/// Size of OWNER_SW_CFG_ROM_EXT_BOOTSTRAP_EN
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_EXT_BOOTSTRAP_EN_SIZE: u32 = 4;
/// Offset of OWNER_SW_CFG_ROM_SENSOR_CTRL_ALERT_CFG
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_SENSOR_CTRL_ALERT_CFG_OFFSET: usize = 964;
/// Size of OWNER_SW_CFG_ROM_SENSOR_CTRL_ALERT_CFG
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_SENSOR_CTRL_ALERT_CFG_SIZE: u32 = 12;
/// Offset of OWNER_SW_CFG_ROM_SRAM_READBACK_EN
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_SRAM_READBACK_EN_OFFSET: usize = 976;
/// Size of OWNER_SW_CFG_ROM_SRAM_READBACK_EN
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_SRAM_READBACK_EN_SIZE: u32 = 4;
/// Offset of OWNER_SW_CFG_ROM_PRESERVE_RESET_REASON_EN
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_PRESERVE_RESET_REASON_EN_OFFSET: usize = 980;
/// Size of OWNER_SW_CFG_ROM_PRESERVE_RESET_REASON_EN
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_PRESERVE_RESET_REASON_EN_SIZE: u32 = 4;
/// Offset of OWNER_SW_CFG_ROM_RESET_REASON_CHECK_VALUE
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_RESET_REASON_CHECK_VALUE_OFFSET: usize = 984;
/// Size of OWNER_SW_CFG_ROM_RESET_REASON_CHECK_VALUE
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_RESET_REASON_CHECK_VALUE_SIZE: u32 = 4;
/// Offset of OWNER_SW_CFG_ROM_BANNER_EN
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_BANNER_EN_OFFSET: usize = 988;
/// Size of OWNER_SW_CFG_ROM_BANNER_EN
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_BANNER_EN_SIZE: u32 = 4;
/// Offset of OWNER_SW_CFG_ROM_FLASH_ECC_EXC_HANDLER_EN
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_FLASH_ECC_EXC_HANDLER_EN_OFFSET: usize = 992;
/// Size of OWNER_SW_CFG_ROM_FLASH_ECC_EXC_HANDLER_EN
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_ROM_FLASH_ECC_EXC_HANDLER_EN_SIZE: u32 = 4;
/// Offset of OWNER_SW_CFG_RESERVED
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_RESERVED_OFFSET: usize = 996;
/// Size of OWNER_SW_CFG_RESERVED
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_RESERVED_SIZE: u32 = 128;
/// Offset of OWNER_SW_CFG_DIGEST
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_DIGEST_OFFSET: usize = 1136;
/// Size of OWNER_SW_CFG_DIGEST
pub const OTP_CTRL_PARAM_OWNER_SW_CFG_DIGEST_SIZE: u32 = 8;
/// Offset of the ROT_CREATOR_AUTH_CODESIGN partition
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_OFFSET: usize = 1144;
/// Size of the ROT_CREATOR_AUTH_CODESIGN partition
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SIZE: u32 = 472;
/// Offset of ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY_TYPE0
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY_TYPE0_OFFSET: usize = 1144;
/// Size of ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY_TYPE0
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY_TYPE0_SIZE: u32 = 4;
/// Offset of ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY0
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY0_OFFSET: usize = 1148;
/// Size of ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY0
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY0_SIZE: u32 = 64;
/// Offset of ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY_TYPE1
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY_TYPE1_OFFSET: usize = 1212;
/// Size of ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY_TYPE1
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY_TYPE1_SIZE: u32 = 4;
/// Offset of ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY1
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY1_OFFSET: usize = 1216;
/// Size of ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY1
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY1_SIZE: u32 = 64;
/// Offset of ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY_TYPE2
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY_TYPE2_OFFSET: usize = 1280;
/// Size of ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY_TYPE2
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY_TYPE2_SIZE: u32 = 4;
/// Offset of ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY2
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY2_OFFSET: usize = 1284;
/// Size of ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY2
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY2_SIZE: u32 = 64;
/// Offset of ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY_TYPE3
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY_TYPE3_OFFSET: usize = 1348;
/// Size of ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY_TYPE3
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY_TYPE3_SIZE: u32 = 4;
/// Offset of ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY3
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY3_OFFSET: usize = 1352;
/// Size of ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY3
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_ECDSA_KEY3_SIZE: u32 = 64;
/// Offset of ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_TYPE0
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_TYPE0_OFFSET: usize = 1416;
/// Size of ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_TYPE0
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_TYPE0_SIZE: u32 = 4;
/// Offset of ROT_CREATOR_AUTH_CODESIGN_SPX_KEY0
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SPX_KEY0_OFFSET: usize = 1420;
/// Size of ROT_CREATOR_AUTH_CODESIGN_SPX_KEY0
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SPX_KEY0_SIZE: u32 = 32;
/// Offset of ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_CONFIG0
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_CONFIG0_OFFSET: usize = 1452;
/// Size of ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_CONFIG0
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_CONFIG0_SIZE: u32 = 4;
/// Offset of ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_TYPE1
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_TYPE1_OFFSET: usize = 1456;
/// Size of ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_TYPE1
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_TYPE1_SIZE: u32 = 4;
/// Offset of ROT_CREATOR_AUTH_CODESIGN_SPX_KEY1
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SPX_KEY1_OFFSET: usize = 1460;
/// Size of ROT_CREATOR_AUTH_CODESIGN_SPX_KEY1
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SPX_KEY1_SIZE: u32 = 32;
/// Offset of ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_CONFIG1
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_CONFIG1_OFFSET: usize = 1492;
/// Size of ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_CONFIG1
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_CONFIG1_SIZE: u32 = 4;
/// Offset of ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_TYPE2
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_TYPE2_OFFSET: usize = 1496;
/// Size of ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_TYPE2
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_TYPE2_SIZE: u32 = 4;
/// Offset of ROT_CREATOR_AUTH_CODESIGN_SPX_KEY2
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SPX_KEY2_OFFSET: usize = 1500;
/// Size of ROT_CREATOR_AUTH_CODESIGN_SPX_KEY2
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SPX_KEY2_SIZE: u32 = 32;
/// Offset of ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_CONFIG2
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_CONFIG2_OFFSET: usize = 1532;
/// Size of ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_CONFIG2
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_CONFIG2_SIZE: u32 = 4;
/// Offset of ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_TYPE3
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_TYPE3_OFFSET: usize = 1536;
/// Size of ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_TYPE3
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_TYPE3_SIZE: u32 = 4;
/// Offset of ROT_CREATOR_AUTH_CODESIGN_SPX_KEY3
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SPX_KEY3_OFFSET: usize = 1540;
/// Size of ROT_CREATOR_AUTH_CODESIGN_SPX_KEY3
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SPX_KEY3_SIZE: u32 = 32;
/// Offset of ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_CONFIG3
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_CONFIG3_OFFSET: usize = 1572;
/// Size of ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_CONFIG3
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_SPX_KEY_CONFIG3_SIZE: u32 = 4;
/// Offset of ROT_CREATOR_AUTH_CODESIGN_BLOCK_SHA2_256_HASH
pub const OTP_CTRL_PARAM_ROTCREATORAUTHCODESIGNBLOCKSHA2_256HASHOFFSET: u32 = 1576;
/// Size of ROT_CREATOR_AUTH_CODESIGN_BLOCK_SHA2_256_HASH
pub const OTP_CTRL_PARAM_ROTCREATORAUTHCODESIGNBLOCKSHA2_256HASHSIZE: u32 = 32;
/// Offset of ROT_CREATOR_AUTH_CODESIGN_DIGEST
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_DIGEST_OFFSET: usize = 1608;
/// Size of ROT_CREATOR_AUTH_CODESIGN_DIGEST
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_CODESIGN_DIGEST_SIZE: u32 = 8;
/// Offset of the ROT_CREATOR_AUTH_STATE partition
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_STATE_OFFSET: usize = 1616;
/// Size of the ROT_CREATOR_AUTH_STATE partition
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_STATE_SIZE: u32 = 40;
/// Offset of ROT_CREATOR_AUTH_STATE_ECDSA_KEY0
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_STATE_ECDSA_KEY0_OFFSET: usize = 1616;
/// Size of ROT_CREATOR_AUTH_STATE_ECDSA_KEY0
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_STATE_ECDSA_KEY0_SIZE: u32 = 4;
/// Offset of ROT_CREATOR_AUTH_STATE_ECDSA_KEY1
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_STATE_ECDSA_KEY1_OFFSET: usize = 1620;
/// Size of ROT_CREATOR_AUTH_STATE_ECDSA_KEY1
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_STATE_ECDSA_KEY1_SIZE: u32 = 4;
/// Offset of ROT_CREATOR_AUTH_STATE_ECDSA_KEY2
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_STATE_ECDSA_KEY2_OFFSET: usize = 1624;
/// Size of ROT_CREATOR_AUTH_STATE_ECDSA_KEY2
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_STATE_ECDSA_KEY2_SIZE: u32 = 4;
/// Offset of ROT_CREATOR_AUTH_STATE_ECDSA_KEY3
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_STATE_ECDSA_KEY3_OFFSET: usize = 1628;
/// Size of ROT_CREATOR_AUTH_STATE_ECDSA_KEY3
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_STATE_ECDSA_KEY3_SIZE: u32 = 4;
/// Offset of ROT_CREATOR_AUTH_STATE_SPX_KEY0
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_STATE_SPX_KEY0_OFFSET: usize = 1632;
/// Size of ROT_CREATOR_AUTH_STATE_SPX_KEY0
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_STATE_SPX_KEY0_SIZE: u32 = 4;
/// Offset of ROT_CREATOR_AUTH_STATE_SPX_KEY1
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_STATE_SPX_KEY1_OFFSET: usize = 1636;
/// Size of ROT_CREATOR_AUTH_STATE_SPX_KEY1
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_STATE_SPX_KEY1_SIZE: u32 = 4;
/// Offset of ROT_CREATOR_AUTH_STATE_SPX_KEY2
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_STATE_SPX_KEY2_OFFSET: usize = 1640;
/// Size of ROT_CREATOR_AUTH_STATE_SPX_KEY2
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_STATE_SPX_KEY2_SIZE: u32 = 4;
/// Offset of ROT_CREATOR_AUTH_STATE_SPX_KEY3
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_STATE_SPX_KEY3_OFFSET: usize = 1644;
/// Size of ROT_CREATOR_AUTH_STATE_SPX_KEY3
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_STATE_SPX_KEY3_SIZE: u32 = 4;
/// Offset of ROT_CREATOR_AUTH_STATE_DIGEST
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_STATE_DIGEST_OFFSET: usize = 1648;
/// Size of ROT_CREATOR_AUTH_STATE_DIGEST
pub const OTP_CTRL_PARAM_ROT_CREATOR_AUTH_STATE_DIGEST_SIZE: u32 = 8;
/// Offset of the HW_CFG0 partition
pub const OTP_CTRL_PARAM_HW_CFG0_OFFSET: usize = 1656;
/// Size of the HW_CFG0 partition
pub const OTP_CTRL_PARAM_HW_CFG0_SIZE: u32 = 72;
/// Offset of DEVICE_ID
pub const OTP_CTRL_PARAM_DEVICE_ID_OFFSET: usize = 1656;
/// Size of DEVICE_ID
pub const OTP_CTRL_PARAM_DEVICE_ID_SIZE: u32 = 32;
/// Offset of MANUF_STATE
pub const OTP_CTRL_PARAM_MANUF_STATE_OFFSET: usize = 1688;
/// Size of MANUF_STATE
pub const OTP_CTRL_PARAM_MANUF_STATE_SIZE: u32 = 32;
/// Offset of HW_CFG0_DIGEST
pub const OTP_CTRL_PARAM_HW_CFG0_DIGEST_OFFSET: usize = 1720;
/// Size of HW_CFG0_DIGEST
pub const OTP_CTRL_PARAM_HW_CFG0_DIGEST_SIZE: u32 = 8;
/// Offset of the HW_CFG1 partition
pub const OTP_CTRL_PARAM_HW_CFG1_OFFSET: usize = 1728;
/// Size of the HW_CFG1 partition
pub const OTP_CTRL_PARAM_HW_CFG1_SIZE: u32 = 16;
/// Offset of EN_SRAM_IFETCH
pub const OTP_CTRL_PARAM_EN_SRAM_IFETCH_OFFSET: usize = 1728;
/// Size of EN_SRAM_IFETCH
pub const OTP_CTRL_PARAM_EN_SRAM_IFETCH_SIZE: u32 = 1;
/// Offset of EN_CSRNG_SW_APP_READ
pub const OTP_CTRL_PARAM_EN_CSRNG_SW_APP_READ_OFFSET: usize = 1729;
/// Size of EN_CSRNG_SW_APP_READ
pub const OTP_CTRL_PARAM_EN_CSRNG_SW_APP_READ_SIZE: u32 = 1;
/// Offset of DIS_RV_DM_LATE_DEBUG
pub const OTP_CTRL_PARAM_DIS_RV_DM_LATE_DEBUG_OFFSET: usize = 1730;
/// Size of DIS_RV_DM_LATE_DEBUG
pub const OTP_CTRL_PARAM_DIS_RV_DM_LATE_DEBUG_SIZE: u32 = 1;
/// Offset of HW_CFG1_DIGEST
pub const OTP_CTRL_PARAM_HW_CFG1_DIGEST_OFFSET: usize = 1736;
/// Size of HW_CFG1_DIGEST
pub const OTP_CTRL_PARAM_HW_CFG1_DIGEST_SIZE: u32 = 8;
/// Offset of the SECRET0 partition
pub const OTP_CTRL_PARAM_SECRET0_OFFSET: usize = 1744;
/// Size of the SECRET0 partition
pub const OTP_CTRL_PARAM_SECRET0_SIZE: u32 = 40;
/// Offset of TEST_UNLOCK_TOKEN
pub const OTP_CTRL_PARAM_TEST_UNLOCK_TOKEN_OFFSET: usize = 1744;
/// Size of TEST_UNLOCK_TOKEN
pub const OTP_CTRL_PARAM_TEST_UNLOCK_TOKEN_SIZE: u32 = 16;
/// Offset of TEST_EXIT_TOKEN
pub const OTP_CTRL_PARAM_TEST_EXIT_TOKEN_OFFSET: usize = 1760;
/// Size of TEST_EXIT_TOKEN
pub const OTP_CTRL_PARAM_TEST_EXIT_TOKEN_SIZE: u32 = 16;
/// Offset of SECRET0_DIGEST
pub const OTP_CTRL_PARAM_SECRET0_DIGEST_OFFSET: usize = 1776;
/// Size of SECRET0_DIGEST
pub const OTP_CTRL_PARAM_SECRET0_DIGEST_SIZE: u32 = 8;
/// Offset of the SECRET1 partition
pub const OTP_CTRL_PARAM_SECRET1_OFFSET: usize = 1784;
/// Size of the SECRET1 partition
pub const OTP_CTRL_PARAM_SECRET1_SIZE: u32 = 88;
/// Offset of FLASH_ADDR_KEY_SEED
pub const OTP_CTRL_PARAM_FLASH_ADDR_KEY_SEED_OFFSET: usize = 1784;
/// Size of FLASH_ADDR_KEY_SEED
pub const OTP_CTRL_PARAM_FLASH_ADDR_KEY_SEED_SIZE: u32 = 32;
/// Offset of FLASH_DATA_KEY_SEED
pub const OTP_CTRL_PARAM_FLASH_DATA_KEY_SEED_OFFSET: usize = 1816;
/// Size of FLASH_DATA_KEY_SEED
pub const OTP_CTRL_PARAM_FLASH_DATA_KEY_SEED_SIZE: u32 = 32;
/// Offset of SRAM_DATA_KEY_SEED
pub const OTP_CTRL_PARAM_SRAM_DATA_KEY_SEED_OFFSET: usize = 1848;
/// Size of SRAM_DATA_KEY_SEED
pub const OTP_CTRL_PARAM_SRAM_DATA_KEY_SEED_SIZE: u32 = 16;
/// Offset of SECRET1_DIGEST
pub const OTP_CTRL_PARAM_SECRET1_DIGEST_OFFSET: usize = 1864;
/// Size of SECRET1_DIGEST
pub const OTP_CTRL_PARAM_SECRET1_DIGEST_SIZE: u32 = 8;
/// Offset of the SECRET2 partition
pub const OTP_CTRL_PARAM_SECRET2_OFFSET: usize = 1872;
/// Size of the SECRET2 partition
pub const OTP_CTRL_PARAM_SECRET2_SIZE: u32 = 88;
/// Offset of RMA_TOKEN
pub const OTP_CTRL_PARAM_RMA_TOKEN_OFFSET: usize = 1872;
/// Size of RMA_TOKEN
pub const OTP_CTRL_PARAM_RMA_TOKEN_SIZE: u32 = 16;
/// Offset of CREATOR_ROOT_KEY_SHARE0
pub const OTP_CTRL_PARAM_CREATOR_ROOT_KEY_SHARE0_OFFSET: usize = 1888;
/// Size of CREATOR_ROOT_KEY_SHARE0
pub const OTP_CTRL_PARAM_CREATOR_ROOT_KEY_SHARE0_SIZE: u32 = 32;
/// Offset of CREATOR_ROOT_KEY_SHARE1
pub const OTP_CTRL_PARAM_CREATOR_ROOT_KEY_SHARE1_OFFSET: usize = 1920;
/// Size of CREATOR_ROOT_KEY_SHARE1
pub const OTP_CTRL_PARAM_CREATOR_ROOT_KEY_SHARE1_SIZE: u32 = 32;
/// Offset of SECRET2_DIGEST
pub const OTP_CTRL_PARAM_SECRET2_DIGEST_OFFSET: usize = 1952;
/// Size of SECRET2_DIGEST
pub const OTP_CTRL_PARAM_SECRET2_DIGEST_SIZE: u32 = 8;
/// Offset of the LIFE_CYCLE partition
pub const OTP_CTRL_PARAM_LIFE_CYCLE_OFFSET: usize = 1960;
/// Size of the LIFE_CYCLE partition
pub const OTP_CTRL_PARAM_LIFE_CYCLE_SIZE: u32 = 88;
/// Offset of LC_TRANSITION_CNT
pub const OTP_CTRL_PARAM_LC_TRANSITION_CNT_OFFSET: usize = 1960;
/// Size of LC_TRANSITION_CNT
pub const OTP_CTRL_PARAM_LC_TRANSITION_CNT_SIZE: u32 = 48;
/// Offset of LC_STATE
pub const OTP_CTRL_PARAM_LC_STATE_OFFSET: usize = 2008;
/// Size of LC_STATE
pub const OTP_CTRL_PARAM_LC_STATE_SIZE: u32 = 40;
/// Number of alerts
pub const OTP_CTRL_PARAM_NUM_ALERTS: u32 = 5;
/// Register width
pub const OTP_CTRL_PARAM_REG_WIDTH: u32 = 32;

register_structs! {
    pub OtpCtrlRegisters {
        /// Interrupt State Register
        (0x0000 => pub intr_state: ReadWrite<u32, INTR::Register>),
        /// Interrupt Enable Register
        (0x0004 => pub intr_enable: ReadWrite<u32, INTR::Register>),
        /// Interrupt Test Register
        (0x0008 => pub intr_test: ReadWrite<u32, INTR::Register>),
        /// Alert Test Register
        (0x000c => pub alert_test: ReadWrite<u32, ALERT_TEST::Register>),
        /// OTP status register.
        (0x0010 => pub status: ReadWrite<u32, STATUS::Register>),
        /// This register holds information about error conditions that occurred in the agents
        (0x0014 => pub err_code: [ReadWrite<u32, ERR_CODE::Register>; 13]),
        /// Register write enable for all direct access interface registers.
        (0x0048 => pub direct_access_regwen: ReadWrite<u32, DIRECT_ACCESS_REGWEN::Register>),
        /// Command register for direct accesses.
        (0x004c => pub direct_access_cmd: ReadWrite<u32, DIRECT_ACCESS_CMD::Register>),
        /// Address register for direct accesses.
        (0x0050 => pub direct_access_address: ReadWrite<u32, DIRECT_ACCESS_ADDRESS::Register>),
        /// Write data for direct accesses.
        (0x0054 => pub direct_access_wdata: [ReadWrite<u32, DIRECT_ACCESS_WDATA::Register>; 2]),
        /// Read data for direct accesses.
        (0x005c => pub direct_access_rdata: [ReadWrite<u32, DIRECT_ACCESS_RDATA::Register>; 2]),
        /// Register write enable for !!CHECK_TRIGGER.
        (0x0064 => pub check_trigger_regwen: ReadWrite<u32, CHECK_TRIGGER_REGWEN::Register>),
        /// Command register for direct accesses.
        (0x0068 => pub check_trigger: ReadWrite<u32, CHECK_TRIGGER::Register>),
        /// Register write enable for !!INTEGRITY_CHECK_PERIOD and !!CONSISTENCY_CHECK_PERIOD.
        (0x006c => pub check_regwen: ReadWrite<u32, CHECK_REGWEN::Register>),
        /// Timeout value for the integrity and consistency checks.
        (0x0070 => pub check_timeout: ReadWrite<u32, CHECK_TIMEOUT::Register>),
        /// This value specifies the maximum period that can be generated pseudo-randomly.
        (0x0074 => pub integrity_check_period: ReadWrite<u32, INTEGRITY_CHECK_PERIOD::Register>),
        /// This value specifies the maximum period that can be generated pseudo-randomly.
        (0x0078 => pub consistency_check_period: ReadWrite<u32, CONSISTENCY_CHECK_PERIOD::Register>),
        /// Runtime read lock for the VENDOR_TEST partition.
        (0x007c => pub vendor_test_read_lock: ReadWrite<u32, VENDOR_TEST_READ_LOCK::Register>),
        /// Runtime read lock for the CREATOR_SW_CFG partition.
        (0x0080 => pub creator_sw_cfg_read_lock: ReadWrite<u32, CREATOR_SW_CFG_READ_LOCK::Register>),
        /// Runtime read lock for the OWNER_SW_CFG partition.
        (0x0084 => pub owner_sw_cfg_read_lock: ReadWrite<u32, OWNER_SW_CFG_READ_LOCK::Register>),
        /// Runtime read lock for the ROT_CREATOR_AUTH_CODESIGN partition.
        (0x0088 => pub rot_creator_auth_codesign_read_lock: ReadWrite<u32, ROT_CREATOR_AUTH_CODESIGN_READ_LOCK::Register>),
        /// Runtime read lock for the ROT_CREATOR_AUTH_STATE partition.
        (0x008c => pub rot_creator_auth_state_read_lock: ReadWrite<u32, ROT_CREATOR_AUTH_STATE_READ_LOCK::Register>),
        /// Integrity digest for the VENDOR_TEST partition.
        (0x0090 => pub vendor_test_digest: [ReadWrite<u32, VENDOR_TEST_DIGEST::Register>; 2]),
        /// Integrity digest for the CREATOR_SW_CFG partition.
        (0x0098 => pub creator_sw_cfg_digest: [ReadWrite<u32, CREATOR_SW_CFG_DIGEST::Register>; 2]),
        /// Integrity digest for the OWNER_SW_CFG partition.
        (0x00a0 => pub owner_sw_cfg_digest: [ReadWrite<u32, OWNER_SW_CFG_DIGEST::Register>; 2]),
        /// Integrity digest for the ROT_CREATOR_AUTH_CODESIGN partition.
        (0x00a8 => pub rot_creator_auth_codesign_digest: [ReadWrite<u32, ROT_CREATOR_AUTH_CODESIGN_DIGEST::Register>; 2]),
        /// Integrity digest for the ROT_CREATOR_AUTH_STATE partition.
        (0x00b0 => pub rot_creator_auth_state_digest: [ReadWrite<u32, ROT_CREATOR_AUTH_STATE_DIGEST::Register>; 2]),
        /// Integrity digest for the HW_CFG0 partition.
        (0x00b8 => pub hw_cfg0_digest: [ReadWrite<u32, HW_CFG0_DIGEST::Register>; 2]),
        /// Integrity digest for the HW_CFG1 partition.
        (0x00c0 => pub hw_cfg1_digest: [ReadWrite<u32, HW_CFG1_DIGEST::Register>; 2]),
        /// Integrity digest for the SECRET0 partition.
        (0x00c8 => pub secret0_digest: [ReadWrite<u32, SECRET0_DIGEST::Register>; 2]),
        /// Integrity digest for the SECRET1 partition.
        (0x00d0 => pub secret1_digest: [ReadWrite<u32, SECRET1_DIGEST::Register>; 2]),
        /// Integrity digest for the SECRET2 partition.
        (0x00d8 => pub secret2_digest: [ReadWrite<u32, SECRET2_DIGEST::Register>; 2]),
        (0x00e0 => _reserved1),
        /// Memory area: Any read to this window directly maps to the corresponding offset in the creator
        /// and owner software
        (0x0800 => pub sw_cfg_window: [ReadOnly<u32>; 512]),
        (0x1000 => @END),
    }
}

register_bitfields![u32,
    /// Common Interrupt Offsets
    pub INTR [
        OTP_OPERATION_DONE OFFSET(0) NUMBITS(1) [],
        OTP_ERROR OFFSET(1) NUMBITS(1) [],
    ],
    pub ALERT_TEST [
        FATAL_MACRO_ERROR OFFSET(0) NUMBITS(1) [],
        FATAL_CHECK_ERROR OFFSET(1) NUMBITS(1) [],
        FATAL_BUS_INTEG_ERROR OFFSET(2) NUMBITS(1) [],
        FATAL_PRIM_OTP_ALERT OFFSET(3) NUMBITS(1) [],
        RECOV_PRIM_OTP_ALERT OFFSET(4) NUMBITS(1) [],
    ],
    pub STATUS [
        VENDOR_TEST_ERROR OFFSET(0) NUMBITS(1) [],
        CREATOR_SW_CFG_ERROR OFFSET(1) NUMBITS(1) [],
        OWNER_SW_CFG_ERROR OFFSET(2) NUMBITS(1) [],
        ROT_CREATOR_AUTH_CODESIGN_ERROR OFFSET(3) NUMBITS(1) [],
        ROT_CREATOR_AUTH_STATE_ERROR OFFSET(4) NUMBITS(1) [],
        HW_CFG0_ERROR OFFSET(5) NUMBITS(1) [],
        HW_CFG1_ERROR OFFSET(6) NUMBITS(1) [],
        SECRET0_ERROR OFFSET(7) NUMBITS(1) [],
        SECRET1_ERROR OFFSET(8) NUMBITS(1) [],
        SECRET2_ERROR OFFSET(9) NUMBITS(1) [],
        LIFE_CYCLE_ERROR OFFSET(10) NUMBITS(1) [],
        DAI_ERROR OFFSET(11) NUMBITS(1) [],
        LCI_ERROR OFFSET(12) NUMBITS(1) [],
        TIMEOUT_ERROR OFFSET(13) NUMBITS(1) [],
        LFSR_FSM_ERROR OFFSET(14) NUMBITS(1) [],
        SCRAMBLING_FSM_ERROR OFFSET(15) NUMBITS(1) [],
        KEY_DERIV_FSM_ERROR OFFSET(16) NUMBITS(1) [],
        BUS_INTEG_ERROR OFFSET(17) NUMBITS(1) [],
        DAI_IDLE OFFSET(18) NUMBITS(1) [],
        CHECK_PENDING OFFSET(19) NUMBITS(1) [],
    ],
    pub ERR_CODE [
        ERR_CODE_0 OFFSET(0) NUMBITS(3) [
            NO_ERROR = 0,
            MACRO_ERROR = 1,
            MACRO_ECC_CORR_ERROR = 2,
            MACRO_ECC_UNCORR_ERROR = 3,
            MACRO_WRITE_BLANK_ERROR = 4,
            ACCESS_ERROR = 5,
            CHECK_FAIL_ERROR = 6,
            FSM_STATE_ERROR = 7,
        ],
    ],
    pub DIRECT_ACCESS_REGWEN [
        DIRECT_ACCESS_REGWEN OFFSET(0) NUMBITS(1) [],
    ],
    pub DIRECT_ACCESS_CMD [
        RD OFFSET(0) NUMBITS(1) [],
        WR OFFSET(1) NUMBITS(1) [],
        DIGEST OFFSET(2) NUMBITS(1) [],
    ],
    pub DIRECT_ACCESS_ADDRESS [
        DIRECT_ACCESS_ADDRESS OFFSET(0) NUMBITS(11) [],
    ],
    pub DIRECT_ACCESS_WDATA [
        DIRECT_ACCESS_WDATA_0 OFFSET(0) NUMBITS(32) [],
    ],
    pub DIRECT_ACCESS_RDATA [
        DIRECT_ACCESS_RDATA_0 OFFSET(0) NUMBITS(32) [],
    ],
    pub CHECK_TRIGGER_REGWEN [
        CHECK_TRIGGER_REGWEN OFFSET(0) NUMBITS(1) [],
    ],
    pub CHECK_TRIGGER [
        INTEGRITY OFFSET(0) NUMBITS(1) [],
        CONSISTENCY OFFSET(1) NUMBITS(1) [],
    ],
    pub CHECK_REGWEN [
        CHECK_REGWEN OFFSET(0) NUMBITS(1) [],
    ],
    pub CHECK_TIMEOUT [
        CHECK_TIMEOUT OFFSET(0) NUMBITS(32) [],
    ],
    pub INTEGRITY_CHECK_PERIOD [
        INTEGRITY_CHECK_PERIOD OFFSET(0) NUMBITS(32) [],
    ],
    pub CONSISTENCY_CHECK_PERIOD [
        CONSISTENCY_CHECK_PERIOD OFFSET(0) NUMBITS(32) [],
    ],
    pub VENDOR_TEST_READ_LOCK [
        VENDOR_TEST_READ_LOCK OFFSET(0) NUMBITS(1) [],
    ],
    pub CREATOR_SW_CFG_READ_LOCK [
        CREATOR_SW_CFG_READ_LOCK OFFSET(0) NUMBITS(1) [],
    ],
    pub OWNER_SW_CFG_READ_LOCK [
        OWNER_SW_CFG_READ_LOCK OFFSET(0) NUMBITS(1) [],
    ],
    pub ROT_CREATOR_AUTH_CODESIGN_READ_LOCK [
        ROT_CREATOR_AUTH_CODESIGN_READ_LOCK OFFSET(0) NUMBITS(1) [],
    ],
    pub ROT_CREATOR_AUTH_STATE_READ_LOCK [
        ROT_CREATOR_AUTH_STATE_READ_LOCK OFFSET(0) NUMBITS(1) [],
    ],
    pub VENDOR_TEST_DIGEST [
        VENDOR_TEST_DIGEST_0 OFFSET(0) NUMBITS(32) [],
    ],
    pub CREATOR_SW_CFG_DIGEST [
        CREATOR_SW_CFG_DIGEST_0 OFFSET(0) NUMBITS(32) [],
    ],
    pub OWNER_SW_CFG_DIGEST [
        OWNER_SW_CFG_DIGEST_0 OFFSET(0) NUMBITS(32) [],
    ],
    pub ROT_CREATOR_AUTH_CODESIGN_DIGEST [
        ROT_CREATOR_AUTH_CODESIGN_DIGEST_0 OFFSET(0) NUMBITS(32) [],
    ],
    pub ROT_CREATOR_AUTH_STATE_DIGEST [
        ROT_CREATOR_AUTH_STATE_DIGEST_0 OFFSET(0) NUMBITS(32) [],
    ],
    pub HW_CFG0_DIGEST [
        HW_CFG0_DIGEST_0 OFFSET(0) NUMBITS(32) [],
    ],
    pub HW_CFG1_DIGEST [
        HW_CFG1_DIGEST_0 OFFSET(0) NUMBITS(32) [],
    ],
    pub SECRET0_DIGEST [
        SECRET0_DIGEST_0 OFFSET(0) NUMBITS(32) [],
    ],
    pub SECRET1_DIGEST [
        SECRET1_DIGEST_0 OFFSET(0) NUMBITS(32) [],
    ],
    pub SECRET2_DIGEST [
        SECRET2_DIGEST_0 OFFSET(0) NUMBITS(32) [],
    ],
];

// End generated register constants for otp_ctrl
